//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonu
    {
        public int BonusId { get; set; }
        public int EmpId { get; set; }
        public double BonusAmount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
